<?php
return [
    new \Railt\Parser\Rule\Repetition(0, 0, -1, [3], null),
    new \Railt\Parser\Rule\Repetition(1, 0, -1, [4], null),
    new \Railt\Parser\Rule\Concatenation(2, [0, 1], '#Document'),
    new \Railt\Parser\Rule\Concatenation(3, [233], null),
    new \Railt\Parser\Rule\Alternation(4, [226, 200], null),
    new \Railt\Parser\Rule\Token(5, 'T_NAME', true),
    new \Railt\Parser\Rule\Token(6, 'T_TRUE', true),
    new \Railt\Parser\Rule\Token(7, 'T_FALSE', true),
    new \Railt\Parser\Rule\Token(8, 'T_NULL', true),
    new \Railt\Parser\Rule\Alternation(9, [26, 6, 7, 8], null),
    new \Railt\Parser\Rule\Concatenation(10, [9], '#Name'),
    new \Railt\Parser\Rule\Token(11, 'T_NAMESPACE', true),
    new \Railt\Parser\Rule\Token(12, 'T_EXTENDS', true),
    new \Railt\Parser\Rule\Token(13, 'T_IMPLEMENTS', true),
    new \Railt\Parser\Rule\Token(14, 'T_ON', true),
    new \Railt\Parser\Rule\Token(15, 'T_TYPE', true),
    new \Railt\Parser\Rule\Token(16, 'T_ENUM', true),
    new \Railt\Parser\Rule\Token(17, 'T_UNION', true),
    new \Railt\Parser\Rule\Token(18, 'T_INPUT_UNION', true),
    new \Railt\Parser\Rule\Token(19, 'T_INTERFACE', true),
    new \Railt\Parser\Rule\Token(20, 'T_SCHEMA', true),
    new \Railt\Parser\Rule\Token(21, 'T_SCALAR', true),
    new \Railt\Parser\Rule\Token(22, 'T_DIRECTIVE', true),
    new \Railt\Parser\Rule\Token(23, 'T_INPUT', true),
    new \Railt\Parser\Rule\Token(24, 'T_EXTEND', true),
    new \Railt\Parser\Rule\Token(25, 'T_FRAGMENT', true),
    new \Railt\Parser\Rule\Alternation(26, [5, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], null),
    new \Railt\Parser\Rule\Token(27, 'T_VARIABLE', true),
    new \Railt\Parser\Rule\Concatenation(28, [27], '#Variable'),
    new \Railt\Parser\Rule\Repetition(29, 0, 1, [35], null),
    new \Railt\Parser\Rule\Concatenation(30, [29, 31, 10], '#TypeName'),
    new \Railt\Parser\Rule\Token(31, 'T_NAMESPACE_SEPARATOR', false),
    new \Railt\Parser\Rule\Concatenation(32, [10, 31], null),
    new \Railt\Parser\Rule\Repetition(31, 0, -1, [32], null),
    new \Railt\Parser\Rule\Token(34, 'T_NAMESPACE_SEPARATOR', false),
    new \Railt\Parser\Rule\Concatenation(35, [34], '#GlobalTypeNamespace'),
    new \Railt\Parser\Rule\Token(36, 'T_FALSE', true),
    new \Railt\Parser\Rule\Concatenation(37, [36], '#Boolean'),
    new \Railt\Parser\Rule\Token(38, 'T_TRUE', true),
    new \Railt\Parser\Rule\Concatenation(39, [38], '#Boolean'),
    new \Railt\Parser\Rule\Alternation(40, [37, 39], null),
    new \Railt\Parser\Rule\Token(41, 'T_NUMBER', true),
    new \Railt\Parser\Rule\Concatenation(42, [41], '#Number'),
    new \Railt\Parser\Rule\Token(43, 'T_BLOCK_STRING', true),
    new \Railt\Parser\Rule\Concatenation(44, [43], '#String'),
    new \Railt\Parser\Rule\Token(45, 'T_STRING', true),
    new \Railt\Parser\Rule\Concatenation(46, [45], '#String'),
    new \Railt\Parser\Rule\Alternation(47, [44, 46], null),
    new \Railt\Parser\Rule\Token(48, 'T_NULL', true),
    new \Railt\Parser\Rule\Concatenation(49, [48], '#Null'),
    new \Railt\Parser\Rule\Token(50, 'T_BRACE_OPEN', false),
    new \Railt\Parser\Rule\Repetition(51, 0, -1, [55], null),
    new \Railt\Parser\Rule\Token(52, 'T_BRACE_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(53, [50, 51, 52], '#Input'),
    new \Railt\Parser\Rule\Token(54, 'T_COLON', false),
    new \Railt\Parser\Rule\Concatenation(55, [10, 54, 67], '#Pair'),
    new \Railt\Parser\Rule\Token(56, 'T_BRACKET_OPEN', false),
    new \Railt\Parser\Rule\Repetition(57, 0, -1, [67], null),
    new \Railt\Parser\Rule\Token(58, 'T_BRACKET_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(59, [56, 57, 58], '#List'),
    new \Railt\Parser\Rule\Concatenation(60, [10], '#Value'),
    new \Railt\Parser\Rule\Concatenation(61, [40], '#Value'),
    new \Railt\Parser\Rule\Concatenation(62, [42], '#Value'),
    new \Railt\Parser\Rule\Concatenation(63, [47], '#Value'),
    new \Railt\Parser\Rule\Concatenation(64, [53], '#Value'),
    new \Railt\Parser\Rule\Concatenation(65, [49], '#Value'),
    new \Railt\Parser\Rule\Concatenation(66, [59], '#Value'),
    new \Railt\Parser\Rule\Alternation(67, [60, 61, 62, 63, 64, 65, 66], null),
    new \Railt\Parser\Rule\Concatenation(68, [47], '#Description'),
    new \Railt\Parser\Rule\Token(69, 'T_IMPLEMENTS', false),
    new \Railt\Parser\Rule\Token(70, 'T_AND', false),
    new \Railt\Parser\Rule\Concatenation(71, [70, 243], null),
    new \Railt\Parser\Rule\Repetition(72, 0, -1, [71], null),
    new \Railt\Parser\Rule\Concatenation(73, [69, 243, 72], '#Implements'),
    new \Railt\Parser\Rule\Token(74, 'T_PARENTHESIS_OPEN', false),
    new \Railt\Parser\Rule\Repetition(75, 0, -1, [79], null),
    new \Railt\Parser\Rule\Token(76, 'T_PARENTHESIS_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(77, [74, 75, 76], '#TypeArguments'),
    new \Railt\Parser\Rule\Token(78, 'T_COLON', false),
    new \Railt\Parser\Rule\Concatenation(79, [28, 78, 30], '#TypeArgument'),
    new \Railt\Parser\Rule\Concatenation(80, [86], '#TypeHint'),
    new \Railt\Parser\Rule\Concatenation(81, [88], '#TypeHint'),
    new \Railt\Parser\Rule\Alternation(82, [80, 81], null),
    new \Railt\Parser\Rule\Token(83, 'T_BRACKET_OPEN', false),
    new \Railt\Parser\Rule\Token(84, 'T_BRACKET_CLOSE', false),
    new \Railt\Parser\Rule\Repetition(85, 0, 1, [90], null),
    new \Railt\Parser\Rule\Concatenation(86, [83, 88, 84, 85], '#List'),
    new \Railt\Parser\Rule\Repetition(87, 0, 1, [90], null),
    new \Railt\Parser\Rule\Concatenation(88, [243, 87], '#Value'),
    new \Railt\Parser\Rule\Token(89, 'T_NON_NULL', false),
    new \Railt\Parser\Rule\Concatenation(90, [89], '#NonNull'),
    new \Railt\Parser\Rule\Repetition(91, 0, 1, [68], null),
    new \Railt\Parser\Rule\Token(92, 'T_COLON', false),
    new \Railt\Parser\Rule\Repetition(93, 0, 1, [96], null),
    new \Railt\Parser\Rule\Concatenation(94, [91, 10, 92, 82, 93], '#ArgumentDefinition'),
    new \Railt\Parser\Rule\Token(95, 'T_EQUAL', false),
    new \Railt\Parser\Rule\Concatenation(96, [95, 67], null),
    new \Railt\Parser\Rule\Repetition(97, 0, 1, [68], null),
    new \Railt\Parser\Rule\Repetition(98, 0, 1, [104], null),
    new \Railt\Parser\Rule\Token(99, 'T_COLON', false),
    new \Railt\Parser\Rule\Concatenation(100, [97, 10, 98, 99, 82, 230], '#FieldDefinition'),
    new \Railt\Parser\Rule\Token(101, 'T_PARENTHESIS_OPEN', false),
    new \Railt\Parser\Rule\Repetition(102, 0, -1, [105], null),
    new \Railt\Parser\Rule\Token(103, 'T_PARENTHESIS_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(104, [101, 102, 103], '#FieldArguments'),
    new \Railt\Parser\Rule\Concatenation(105, [94, 230], '#FieldArgument'),
    new \Railt\Parser\Rule\Repetition(106, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(107, [106, 112], '#DirectiveDefinition'),
    new \Railt\Parser\Rule\Token(108, 'T_DIRECTIVE', false),
    new \Railt\Parser\Rule\Token(109, 'T_DIRECTIVE_AT', false),
    new \Railt\Parser\Rule\Repetition(110, 0, 1, [116], null),
    new \Railt\Parser\Rule\Token(111, 'T_ON', false),
    new \Railt\Parser\Rule\Concatenation(112, [108, 109, 30, 110, 111, 121], null),
    new \Railt\Parser\Rule\Token(113, 'T_PARENTHESIS_OPEN', false),
    new \Railt\Parser\Rule\Repetition(114, 0, -1, [117], null),
    new \Railt\Parser\Rule\Token(115, 'T_PARENTHESIS_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(116, [113, 114, 115], null),
    new \Railt\Parser\Rule\Concatenation(117, [94], '#DirectiveArgument'),
    new \Railt\Parser\Rule\Token(118, 'T_OR', false),
    new \Railt\Parser\Rule\Repetition(119, 0, 1, [118], null),
    new \Railt\Parser\Rule\Repetition(120, 1, -1, [125], null),
    new \Railt\Parser\Rule\Concatenation(121, [119, 120], '#DirectiveLocations'),
    new \Railt\Parser\Rule\Token(122, 'T_OR', false),
    new \Railt\Parser\Rule\Concatenation(123, [122, 10], null),
    new \Railt\Parser\Rule\Repetition(124, 0, -1, [123], null),
    new \Railt\Parser\Rule\Concatenation(125, [10, 124], null),
    new \Railt\Parser\Rule\Repetition(126, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(127, [126, 129, 133], '#EnumDefinition'),
    new \Railt\Parser\Rule\Token(128, 'T_ENUM', false),
    new \Railt\Parser\Rule\Concatenation(129, [128, 30, 230], null),
    new \Railt\Parser\Rule\Token(130, 'T_BRACE_OPEN', false),
    new \Railt\Parser\Rule\Repetition(131, 1, -1, [135], null),
    new \Railt\Parser\Rule\Token(132, 'T_BRACE_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(133, [130, 131, 132], null),
    new \Railt\Parser\Rule\Repetition(134, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(135, [134, 26, 230], '#EnumValue'),
    new \Railt\Parser\Rule\Repetition(136, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(137, [136, 139, 143], '#InputDefinition'),
    new \Railt\Parser\Rule\Token(138, 'T_INPUT', false),
    new \Railt\Parser\Rule\Concatenation(139, [138, 30, 230], null),
    new \Railt\Parser\Rule\Token(140, 'T_BRACE_OPEN', false),
    new \Railt\Parser\Rule\Repetition(141, 0, -1, [144], null),
    new \Railt\Parser\Rule\Token(142, 'T_BRACE_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(143, [140, 141, 142], null),
    new \Railt\Parser\Rule\Concatenation(144, [94, 230], '#InputField'),
    new \Railt\Parser\Rule\Repetition(145, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(146, [145, 150, 155], '#InterfaceDefinition'),
    new \Railt\Parser\Rule\Token(147, 'T_INTERFACE', false),
    new \Railt\Parser\Rule\Repetition(148, 0, 1, [77], null),
    new \Railt\Parser\Rule\Repetition(149, 0, 1, [73], null),
    new \Railt\Parser\Rule\Concatenation(150, [147, 30, 148, 149, 230], null),
    new \Railt\Parser\Rule\Token(151, 'T_BRACE_OPEN', false),
    new \Railt\Parser\Rule\Repetition(152, 0, 1, [157], null),
    new \Railt\Parser\Rule\Repetition(153, 0, 1, [202], null),
    new \Railt\Parser\Rule\Token(154, 'T_BRACE_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(155, [151, 152, 153, 154], null),
    new \Railt\Parser\Rule\Repetition(156, 0, -1, [100], null),
    new \Railt\Parser\Rule\Concatenation(157, [156], '#FieldDefinitions'),
    new \Railt\Parser\Rule\Repetition(158, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(159, [158, 163, 168], '#ObjectDefinition'),
    new \Railt\Parser\Rule\Token(160, 'T_TYPE', false),
    new \Railt\Parser\Rule\Repetition(161, 0, 1, [77], null),
    new \Railt\Parser\Rule\Repetition(162, 0, 1, [73], null),
    new \Railt\Parser\Rule\Concatenation(163, [160, 30, 161, 162, 230], null),
    new \Railt\Parser\Rule\Token(164, 'T_BRACE_OPEN', false),
    new \Railt\Parser\Rule\Repetition(165, 0, 1, [170], null),
    new \Railt\Parser\Rule\Repetition(166, 0, 1, [202], null),
    new \Railt\Parser\Rule\Token(167, 'T_BRACE_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(168, [164, 165, 166, 167], null),
    new \Railt\Parser\Rule\Repetition(169, 0, -1, [100], null),
    new \Railt\Parser\Rule\Concatenation(170, [169], '#FieldDefinitions'),
    new \Railt\Parser\Rule\Repetition(171, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(172, [171, 175], '#ScalarDefinition'),
    new \Railt\Parser\Rule\Token(173, 'T_SCALAR', false),
    new \Railt\Parser\Rule\Repetition(174, 0, 1, [177], null),
    new \Railt\Parser\Rule\Concatenation(175, [173, 30, 174, 230], null),
    new \Railt\Parser\Rule\Token(176, 'T_EXTENDS', false),
    new \Railt\Parser\Rule\Concatenation(177, [176, 30], '#Extends'),
    new \Railt\Parser\Rule\Repetition(178, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(179, [178, 185], '#SchemaDefinition'),
    new \Railt\Parser\Rule\Token(180, 'T_SCHEMA', false),
    new \Railt\Parser\Rule\Repetition(181, 0, 1, [30], null),
    new \Railt\Parser\Rule\Token(182, 'T_BRACE_OPEN', false),
    new \Railt\Parser\Rule\Repetition(183, 0, -1, [187], null),
    new \Railt\Parser\Rule\Token(184, 'T_BRACE_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(185, [180, 181, 182, 183, 184], null),
    new \Railt\Parser\Rule\Token(186, 'T_COLON', false),
    new \Railt\Parser\Rule\Concatenation(187, [10, 186, 30], '#SchemaField'),
    new \Railt\Parser\Rule\Repetition(188, 0, 1, [68], null),
    new \Railt\Parser\Rule\Concatenation(189, [188, 195], '#UnionDefinition'),
    new \Railt\Parser\Rule\Token(190, 'T_UNION', false),
    new \Railt\Parser\Rule\Token(191, 'T_EQUAL', false),
    new \Railt\Parser\Rule\Token(192, 'T_OR', false),
    new \Railt\Parser\Rule\Repetition(193, 0, 1, [192], null),
    new \Railt\Parser\Rule\Repetition(194, 1, -1, [199], null),
    new \Railt\Parser\Rule\Concatenation(195, [190, 30, 230, 191, 193, 194], null),
    new \Railt\Parser\Rule\Token(196, 'T_OR', false),
    new \Railt\Parser\Rule\Concatenation(197, [196, 30], null),
    new \Railt\Parser\Rule\Repetition(198, 0, -1, [197], null),
    new \Railt\Parser\Rule\Concatenation(199, [30, 198], null),
    new \Railt\Parser\Rule\Alternation(200, [107, 179, 203], null),
    new \Railt\Parser\Rule\Concatenation(201, [203], null),
    new \Railt\Parser\Rule\Concatenation(202, [201], '#ChildrenDefinitions'),
    new \Railt\Parser\Rule\Alternation(203, [127, 137, 146, 159, 172, 189], null),
    new \Railt\Parser\Rule\Token(204, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(205, [204, 207], '#EnumExtension'),
    new \Railt\Parser\Rule\Concatenation(206, [129, 133], null),
    new \Railt\Parser\Rule\Alternation(207, [129, 206], null),
    new \Railt\Parser\Rule\Token(208, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(209, [208, 211], '#InputExtension'),
    new \Railt\Parser\Rule\Concatenation(210, [139, 143], null),
    new \Railt\Parser\Rule\Alternation(211, [139, 210], null),
    new \Railt\Parser\Rule\Token(212, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(213, [212, 215], '#InterfaceExtension'),
    new \Railt\Parser\Rule\Concatenation(214, [150, 155], null),
    new \Railt\Parser\Rule\Alternation(215, [150, 214], null),
    new \Railt\Parser\Rule\Token(216, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(217, [216, 219], '#ObjectExtension'),
    new \Railt\Parser\Rule\Concatenation(218, [163, 168], null),
    new \Railt\Parser\Rule\Alternation(219, [163, 218], null),
    new \Railt\Parser\Rule\Token(220, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(221, [220, 175], '#ScalarExtension'),
    new \Railt\Parser\Rule\Token(222, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(223, [222, 185], '#SchemaExtension'),
    new \Railt\Parser\Rule\Token(224, 'T_EXTEND', false),
    new \Railt\Parser\Rule\Concatenation(225, [224, 195], '#UnionExtension'),
    new \Railt\Parser\Rule\Alternation(226, [205, 209, 213, 217, 221, 223, 225], null),
    new \Railt\Parser\Rule\Token(227, 'T_COLON', false),
    new \Railt\Parser\Rule\Concatenation(228, [10, 227, 67], null),
    new \Railt\Parser\Rule\Repetition(229, 0, -1, [233], null),
    new \Railt\Parser\Rule\Concatenation(230, [229], '#Directives'),
    new \Railt\Parser\Rule\Token(231, 'T_DIRECTIVE_AT', false),
    new \Railt\Parser\Rule\Repetition(232, 0, 1, [237], null),
    new \Railt\Parser\Rule\Concatenation(233, [231, 30, 232], '#Directive'),
    new \Railt\Parser\Rule\Token(234, 'T_PARENTHESIS_OPEN', false),
    new \Railt\Parser\Rule\Repetition(235, 0, -1, [238], null),
    new \Railt\Parser\Rule\Token(236, 'T_PARENTHESIS_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(237, [234, 235, 236], null),
    new \Railt\Parser\Rule\Concatenation(238, [228], '#DirectiveArgument'),
    new \Railt\Parser\Rule\Concatenation(239, [30], '#TypeInvocation'),
    new \Railt\Parser\Rule\Concatenation(240, [28], '#TypeInvocation'),
    new \Railt\Parser\Rule\Alternation(241, [239, 240], null),
    new \Railt\Parser\Rule\Repetition(242, 0, 1, [247], null),
    new \Railt\Parser\Rule\Concatenation(243, [241, 242], null),
    new \Railt\Parser\Rule\Token(244, 'T_PARENTHESIS_OPEN', false),
    new \Railt\Parser\Rule\Repetition(245, 0, -1, [249], null),
    new \Railt\Parser\Rule\Token(246, 'T_PARENTHESIS_CLOSE', false),
    new \Railt\Parser\Rule\Concatenation(247, [244, 245, 246], '#TypeInvocationArguments'),
    new \Railt\Parser\Rule\Token(248, 'T_COLON', false),
    new \Railt\Parser\Rule\Concatenation(249, [10, 248, 243], '#TypeInvocationArgument'),
    new \Railt\Parser\Rule\Concatenation(250, [233], null),
];
